# Based on Purpur's pipeline
# https://github.com/PurpurMC/Purpur/blob/ver/1.20.6/.github/workflows/build.yml

name: Build and Release
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v2
      - uses: gradle/actions/setup-gradle@v3
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --no-daemon --stacktrace
      - name: Build and publish
        run: ./gradlew createMojmapPaperclipJar publish --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_lucyydotpSnapshotsUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_lucyydotpSnapshotsPassword: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: paperclip
          path: |
            build/libs/marionette-paperclip-*.jar
